# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      sudo apt update
      sudo apt install gh
  displayName: 'Install Github CLI'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $(TOKEN) > token.txt
      gh auth login --with-token < token.txt
      gh auth status
  displayName: 'check Github Auth status'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      gh repo create yelghali/NEWTOTO55 -y  --private --template azure-synapse-devops
  displayName: 'Create Repo from Template'

